### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by slarge** [slarge/dept-overview#1]
- [ ] Add confirmed benchmarks to SD to populate "WK chair", "WK dates", and WK name" fields.
- [ ] Find a permanent home for Issue Lists (maybe consider a better template) and link to the list.
- [ ] Think about how often these should be updated and checks when they are updated automatically.
